In [1]:
import csv
import pickle
from datetime import datetime
from sklearn import preprocessing
import numpy as np
import random
from sklearn.preprocessing import OneHotEncoder
import sys

def csv2dicts(csvfile):
    data = []
    keys = []
    for row_index, row in enumerate(csvfile):
        if row_index == 0:
            keys = row
            print(row)
            continue
        # if row_index % 10000 == 0:
        #     print(row_index)
        data.append({key: value for key, value in zip(keys, row)})
    return data


def set_nan_as_string(data, replace_str='0'):
    for i, x in enumerate(data):
        for key, value in x.items():
            if value == '':
                x[key] = replace_str
        data[i] = x

In [2]:
test_data_filename = "dataset/rossmann/test.csv"
train_data_filename = "dataset/rossmann/train.csv"
store_data_filename = "dataset/rossmann/store.csv"
store_states_filename = 'dataset/rossmann/store_states.csv'

In [3]:
csvfile = open(train_data_filename)
train_data = csv.reader(csvfile, delimiter=',')
train_data = csv2dicts(train_data)
train_data = train_data[::-1]

print(train_data[:3])

['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']
[{'Store': '1115', 'DayOfWeek': '2', 'Date': '2013-01-01', 'Sales': '0', 'Customers': '0', 'Open': '0', 'Promo': '0', 'StateHoliday': 'a', 'SchoolHoliday': '1'}, {'Store': '1114', 'DayOfWeek': '2', 'Date': '2013-01-01', 'Sales': '0', 'Customers': '0', 'Open': '0', 'Promo': '0', 'StateHoliday': 'a', 'SchoolHoliday': '1'}, {'Store': '1113', 'DayOfWeek': '2', 'Date': '2013-01-01', 'Sales': '0', 'Customers': '0', 'Open': '0', 'Promo': '0', 'StateHoliday': 'a', 'SchoolHoliday': '1'}]


In [4]:
csvfile_test = open(test_data_filename)
test_data = csv.reader(csvfile_test, delimiter=',')
test_data = csv2dicts(test_data)
test_data = test_data[::-1]

print(test_data[:3])

['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']
[{'Id': '41088', 'Store': '1115', 'DayOfWeek': '6', 'Date': '2015-08-01', 'Open': '1', 'Promo': '0', 'StateHoliday': '0', 'SchoolHoliday': '1'}, {'Id': '41087', 'Store': '1114', 'DayOfWeek': '6', 'Date': '2015-08-01', 'Open': '1', 'Promo': '0', 'StateHoliday': '0', 'SchoolHoliday': '0'}, {'Id': '41086', 'Store': '1113', 'DayOfWeek': '6', 'Date': '2015-08-01', 'Open': '1', 'Promo': '0', 'StateHoliday': '0', 'SchoolHoliday': '0'}]


In [5]:
csvfile = open(store_data_filename)
csvfile2 = open(store_states_filename)
store_data = csv.reader(csvfile, delimiter=',')
store_states_data = csv.reader(csvfile2, delimiter=',')

store_data = csv2dicts(store_data)
store_states_data = csv2dicts(store_states_data)
set_nan_as_string(store_data)
for index, val in enumerate(store_data):
    state = store_states_data[index]
    val['State'] = state['State']
    store_data[index] = val

print(store_data[:2])

['Store', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']
['Store', 'State']
[{'Store': '1', 'StoreType': 'c', 'Assortment': 'a', 'CompetitionDistance': '1270', 'CompetitionOpenSinceMonth': '9', 'CompetitionOpenSinceYear': '2008', 'Promo2': '0', 'Promo2SinceWeek': '0', 'Promo2SinceYear': '0', 'PromoInterval': '0', 'State': 'HE'}, {'Store': '2', 'StoreType': 'a', 'Assortment': 'a', 'CompetitionDistance': '570', 'CompetitionOpenSinceMonth': '11', 'CompetitionOpenSinceYear': '2007', 'Promo2': '1', 'Promo2SinceWeek': '13', 'Promo2SinceYear': '2010', 'PromoInterval': 'Jan,Apr,Jul,Oct', 'State': 'TH'}]


# Prepare features

In [6]:
random.seed(42)

def feature_list(record):
    dt = datetime.strptime(record['Date'], '%Y-%m-%d')
    store_index = int(record['Store'])
    year = dt.year
    month = dt.month
    day = dt.day
    day_of_week = int(record['DayOfWeek'])
    try:
        store_open = int(record['Open'])
    except:
        store_open = 1

    promo = int(record['Promo'])

    return [store_open,
            store_index,
            day_of_week,
            promo,
            year,
            month,
            day,
            store_data[store_index - 1]['State']
            ]

In [7]:
train_data_X = []
train_data_y = []

for record in train_data:
    if record['Sales'] != '0' and record['Open'] != '':
        fl = feature_list(record)
        train_data_X.append(fl)
        train_data_y.append(int(record['Sales']))
print("Number of train datapoints: ", len(train_data_y))
print(min(train_data_y), max(train_data_y))

Number of train datapoints:  844338
46 41551


In [8]:
train_data_X[:10]

[[1, 1097, 2, 0, 2013, 1, 1, 'RP'],
 [1, 948, 2, 0, 2013, 1, 1, 'BW'],
 [1, 769, 2, 0, 2013, 1, 1, 'NW'],
 [1, 733, 2, 0, 2013, 1, 1, 'NW'],
 [1, 682, 2, 0, 2013, 1, 1, 'BE'],
 [1, 676, 2, 0, 2013, 1, 1, 'HE'],
 [1, 562, 2, 0, 2013, 1, 1, 'HB,NI'],
 [1, 530, 2, 0, 2013, 1, 1, 'SH'],
 [1, 512, 2, 0, 2013, 1, 1, 'BY'],
 [1, 494, 2, 0, 2013, 1, 1, 'BE']]

In [9]:
test_data_X = []
for record in test_data:
    fl = feature_list(record)
    test_data_X.append(fl)

In [10]:
test_data_X[:10]

[[1, 1115, 6, 0, 2015, 8, 1, 'HE'],
 [1, 1114, 6, 0, 2015, 8, 1, 'HH'],
 [1, 1113, 6, 0, 2015, 8, 1, 'SH'],
 [1, 1112, 6, 0, 2015, 8, 1, 'NW'],
 [1, 1111, 6, 0, 2015, 8, 1, 'NW'],
 [1, 1109, 6, 0, 2015, 8, 1, 'BY'],
 [1, 1107, 6, 0, 2015, 8, 1, 'BY'],
 [1, 1106, 6, 0, 2015, 8, 1, 'SH'],
 [1, 1105, 6, 0, 2015, 8, 1, 'NW'],
 [1, 1104, 6, 0, 2015, 8, 1, 'BY']]

In [11]:
full_X = np.array(train_data_X)
train_data_X = np.array(train_data_X)
full_X.shape

(844338, 8)

In [12]:
test_data_X = np.array(test_data_X)
test_data_X.shape

(41088, 8)

In [13]:
train_data_X[:, 0]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U11')

In [14]:
les = []
for i in range(train_data_X.shape[1]):
    le = preprocessing.LabelEncoder()
    le.fit(full_X[:, i])
    les.append(le)
    train_data_X[:, i] = le.transform(train_data_X[:, i])
    if i > 0:
        test_data_X[:, i] = le.transform(test_data_X[:, i])

In [15]:
train_data_X.shape

(844338, 8)

In [16]:
train_data_X = train_data_X.astype(int)
train_data_y = np.array(train_data_y)
# les y  (train_data_X, train_data_y)

In [17]:
print(train_data_X[0], train_data_y[0])

[  0 109   1   0   0   0   0   7] 5961


In [18]:
np.random.seed(123)

sys.setrecursionlimit(10000)

train_ratio = 0.9
shuffle_data = False
one_hot_as_input = False
embeddings_as_input = False
save_embeddings = True
saved_embeddings_fname = "embeddings.pickle"  # set save_embeddings to True to create this file

(X, y) = train_data_X, train_data_y

num_records = len(X)
train_size = int(train_ratio * num_records)

In [19]:
if shuffle_data:
    print("Using shuffled data")
    sh = numpy.arange(X.shape[0])
    np.random.shuffle(sh)
    X = X[sh]
    y = y[sh]

if embeddings_as_input:
    print("Using learned embeddings as input")
    X = embed_features(X, saved_embeddings_fname)

if one_hot_as_input:
    print("Using one-hot encoding as input")
    enc = OneHotEncoder(sparse=False)
    enc.fit(X)
    X = enc.transform(X)

X_train = X[:train_size]
X_val = X[train_size:]
y_train = y[:train_size]
y_val = y[train_size:]

print(X_train.shape, X_val.shape)

(759904, 8) (84434, 8)


In [20]:
def sample(X, y, n):
    '''random samples'''
    num_row = X.shape[0]
    indices = np.random.randint(num_row, size=n)
    return X[indices, :], y[indices]


X_train, y_train = sample(X_train, y_train, 200000)  # Simulate data sparsity
print("Number of samples used for training: " + str(y_train.shape[0]))

Number of samples used for training: 200000


In [21]:
X_train.shape

(200000, 8)

In [22]:
from models import *

In [23]:
models = []

print("Fitting NN_with_EntityEmbedding...")
for i in range(5):
    models.append(NN_with_EntityEmbedding(X_train, y_train, X_val, y_val))

Fitting NN_with_EntityEmbedding...
Epoch 1/10
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0142 - val_loss: 0.0116
Epoch 2/10
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0094 - val_loss: 0.0109
Epoch 3/10
1563/1563 [==============================] - 15s 10ms/step - loss: 0.0085 - val_loss: 0.0105
Epoch 4/10
1563/1563 [==============================] - 16s 10ms/step - loss: 0.0079 - val_loss: 0.0106
Epoch 5/10
1563/1563 [==============================] - 17s 11ms/step - loss: 0.0076 - val_loss: 0.0100
Epoch 6/10
1563/1563 [==============================] - 17s 11ms/step - loss: 0.0073 - val_loss: 0.0099
Epoch 7/10
1563/1563 [==============================] - 18s 12ms/step - loss: 0.0072 - val_loss: 0.0098
Epoch 8/10
1563/1563 [==============================] - 19s 12ms/step - loss: 0.0070 - val_loss: 0.0097
Epoch 9/10
1563/1563 [==============================] - 19s 12ms/step - loss: 0.0069 - val_loss: 0.0094
Epoch 10/10
1563/1563 [========

In [24]:
test_data_X[:, 1:].shape

(41088, 7)

In [41]:
test_data_X

array([['1', '130', '5', ..., '10', '0', '4'],
       ['1', '129', '5', ..., '10', '0', '5'],
       ['1', '128', '5', ..., '10', '0', '8'],
       ...,
       ['1', '782', '3', ..., '11', '8', '8'],
       ['1', '338', '3', ..., '11', '8', '6'],
       ['1', '0', '3', ..., '11', '8', '4']], dtype='<U11')

In [30]:
predictions_norm = models[0].model.predict(np.hsplit(np.array(test_data_X[:, 1:],dtype=float), 7))

In [31]:
y_pred_test = np.exp(predictions_norm * models[0].max_log_y)

In [32]:
y_pred_test[(test_data_X[:, 0] == '0')] = 0

In [33]:
import pandas as pd
sample_csv = pd.read_csv('dataset/rossmann/sample_submission.csv')

In [34]:
sample_csv['Sales'] = y_pred_test

In [35]:
sample_csv.to_csv('submision_mejorado.csv', index=False)

In [36]:
sample_csv.head()

Id         Sales
0   1   9465.942383
1   2  25206.236328
2   3   7143.755371
3   4   6838.359863
4   5   2650.820801

In [42]:
# print("Fitting NN...")
# for i in range(5):
#     models.append(NN(X_train, y_train, X_val, y_val))

# print("Fitting RF...")
# models.append(RF(X_train, y_train, X_val, y_val))

# print("Fitting KNN...")
# models.append(KNN(X_train, y_train, X_val, y_val))

print("Fitting XGBoost...")
models.append(XGBoost(X_train, y_train, X_val, y_val))


if save_embeddings:
    model = models[0].model
    store_embedding = model.get_layer('store_embedding').get_weights()[0]
    dow_embedding = model.get_layer('dow_embedding').get_weights()[0]
    year_embedding = model.get_layer('year_embedding').get_weights()[0]
    month_embedding = model.get_layer('month_embedding').get_weights()[0]
    day_embedding = model.get_layer('day_embedding').get_weights()[0]
    german_states_embedding = model.get_layer('state_embedding').get_weights()[0]
    with open(saved_embeddings_fname, 'wb') as f:
        pickle.dump([store_embedding, dow_embedding, year_embedding,
                     month_embedding, day_embedding, german_states_embedding], f, -1)


def evaluate_models(models, X, y):
    assert(min(y) > 0)
    guessed_sales = numpy.array([model.guess(X) for model in models])
    mean_sales = guessed_sales.mean(axis=0)
    relative_err = numpy.absolute((y - mean_sales) / y)
    result = numpy.sum(relative_err) / len(y)
    return result


print("Evaluate combined models...")
print("Training error...")
r_train = evaluate_models(models, X_train, y_train)
print(r_train)

print("Validation error...")
r_val = evaluate_models(models, X_val, y_val)
print(r_val)

Fitting XGBoost...
[14:52:46] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
[14:52:46] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573: 
Parameters: { "silent" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]	train-rmse:8.09741
[1]	train-rmse:7.93586
[2]	train-rmse:7.77755
[3]	train-rmse:7.62240
[4]	train-rmse:7.47040
[5]	train-rmse:7.32139
[6]	train-rmse:7.17538
[7]	train-rmse:7.03231
[8]	train-rmse:6.89208
[9]	train-rmse:6.75468
[10]	train-rmse:6.62002
[11]	train-rmse:6.48807
[12]	train-rmse:6.35879
[13]	train-rmse:6.23208
[14]	train-rmse:6.10795
[15]	train-rmse:5.98629
[16]	train-rmse:5.86709
[17]	train-rmse:5.75

In [43]:
X_val

array([[  0,  89,   5, ...,   7,  11,   4],
       [  0,  88,   5, ...,   7,  11,   1],
       [  0,  87,   5, ...,   7,  11,   6],
       ...,
       [  0, 338,   4, ...,   9,  24,   6],
       [  0, 227,   4, ...,   9,  24,  11],
       [  0,   0,   4, ...,   9,  24,   4]])

In [44]:
mean_sales

NameError: name 'mean_sales' is not defined

In [ ]:
def evaluate_models_and_save_reslts(models, X, y):
    assert(min(y) > 0)
    guessed_sales = numpy.array([model.guess(X) for model in models])
    mean_sales = guessed_sales.mean(axis=0)
    relative_err = numpy.absolute((y - mean_sales) / y)
    result = numpy.sum(relative_err) / len(y)
    return result

In [47]:
models[5].guess(X_train)

array([ 5213.2563,  2758.5042,  6975.6953, ...,  4684.297 ,  7855.8384,
       15295.472 ], dtype=float32)

In [52]:
models[5].guess(test_data_X)

array([ 6703.6387, 20920.91  ,  5916.617 , ...,  7751.959 ,  6650.3857,
        4276.725 ], dtype=float32)

In [53]:
sample_csv = pd.read_csv('dataset/rossmann/sample_submission.csv')
sample_csv['Sales'] = models[5].guess(test_data_X)
sample_csv.to_csv('submision_mejorado_XGBoost.csv', index=False)