# Defino listas

In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
lista_1 = [1,2,3,4,5]
lista_2 = [6,7,8,9,10]

In [3]:
print(lista_2)

[6, 7, 8, 9, 10]


In [1]:
from helper import suma_arrays

In [6]:
suma_arrays(lista_1, lista_2)

array([ 7,  9, 11, 13, 15])

In [8]:
suma_arrays()

array([ 7,  9, 11, 13, 15])

# Concateno listas

In [9]:
lista_3 = lista_1 + lista_2

In [10]:
print(lista_3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
import numpy as np

In [12]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [9]:
print(array_1 + array_2)

[ 7  9 11 13 15]
