# Defino listas

In [2]:
import numpy as np
np.__version__

'1.19.2'

In [37]:
M = [l*3 for l in lista_1]
print(M)
del M[4]
print(M)

[3, 6, 9, 12, 15]
[3, 6, 9, 12]


In [67]:
arr_1 = np.array([10,  2,  8,  'hey',  6,  5,  4,  1,  9,  3])
print(arr_1)

['10' '2' '8' 'hey' '6' '5' '4' '1' '9' '3']


In [58]:
  arr_1 = np.array([10,  2,  8,  7,  6,  5])
  print(np.argsort(arr_1))

[1 5 4 3 2 0]


In [77]:
import pandas as pd
d = {'col1': [1, '2'], 'col2': [3, '4']}
df = pd.DataFrame(data=d)
print(df)
print(np.array(df['col1']))

  col1 col2
0    1    3
1    2    4
[1 '2']


In [30]:
lista_1 = [1,2,3,4,5]
lista_2 = [6,7,8,9,10]

In [44]:
dictPrueba = {'llave':'valor', 'llave2':'valor2'}
print(dictPrueba.items())

dict_items([('llave', 'valor'), ('llave2', 'valor2')])


In [50]:
x = ['a','b',{'foo': 1,'bar':{'x' : 10,'y' : 20,'z' : 30},'baz': 3},'c','d']
print(x[2]['bar']['z']);
print('asd')
print('asd')

30
asd
asd


In [26]:
print(lista_1[::2])

[11, 3, 5]


In [27]:
print(lista_1)

[11, 2, 3, 4, 5]


In [5]:
from helper import suma_arrays

In [6]:
suma_arrays(lista_1, lista_2)

array([ 7,  9, 11, 13, 15])

In [7]:
suma_arrays()

array([ 7,  9, 11, 13, 15])

In [28]:
x = 1
y = 3
z = 5

if x < z > y:
    print("z es el mayor")

z es el mayor


# Concateno listas

In [18]:
lista_3 = lista_1 + lista_2

In [22]:
print(lista_3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [19]:
lista_1[0] = 11

In [10]:
import numpy as np

In [11]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [12]:
print(array_1 + array_2)

[ 7  9 11 13 15]
